import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './prototype-overrides.css';

const WA_NUMBER = '254182095210';
const MAPS_URL = 'https://www.google.com/maps/dir/?api=1&destination=Westview+Apartments%2C+School+Lane%2C+Westlands%2C+Nairobi%2C+Kenya';
const services = [
  ['Swedish Massage', 4000, 'Long, flowing strokes with warm oils to release surface tension and settle the nervous system.', 'prototype-svc-swedish-Btm3ZN_w.jpg'],
  ['Deep Tissue Massage', 5000, 'Focused, slow pressure through deeper muscle layers to relieve stubborn knots and chronic tightness.', 'prototype-svc-deep-tissue-B6SvPTei.jpg'],
  ['Reflexology', 4000, 'Precise pressure-point work on the feet to ease fatigue and restore balance through the whole body.', 'prototype-svc-reflexology-CSad_R18.jpg'],
  ['Sports Massage', 5000, 'Performance-focused treatment for active bodies — recovery, mobility and injury prevention.', 'prototype-svc-sports-C1_-6ixN.jpg'],
  ['Normal Massage', 4000, 'Our classic full-body relaxation massage at a gentle, unhurried pace. Ideal for first visits.', 'prototype-svc-normal-Nf__ndDF.jpg'],
  ['Sensual Massage', 7000, 'A slow, full-body treatment for adults, delivered with warm oils in a completely private suite.', 'prototype-svc-sensual-Cb0QZ05Q.jpg']
].map(([name, price, description, image], index) => ({ id: `${name}-${price}-${index}`, name, price, description, image }));

const money = (value) => `KSh ${value.toLocaleString('en-KE')}`;
const asset = (name) => `/assets/images/${name}`;
const waLink = `https://wa.me/${WA_NUMBER}?text=${encodeURIComponent('Hello Happy Ending Massage Spa, I would like to make an enquiry.')}`;
const providers = [
  { id: 'amanda', name: 'Amanda', image: 'about-spa.jpg' },
  { id: 'brianna', name: 'Brianna', image: 'hero-spa.jpg' },
  { id: 'carol', name: 'Carol', image: 'normal.jpg' },
  { id: 'diana', name: 'Diana', image: 'sensual.jpg' }
];

function navigate(path) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function Logo({ compact = false }) { return <a className={`brand ${compact ? 'brand--compact' : ''}`} href="/" onClick={(event) => { event.preventDefault(); navigate('/'); }}><img src="/assets/logo-reference.png" alt="Happy Ending Massage Spa logo" /><span><strong>Happy Ending Massage Spa</strong><small>Luxury Massage & Wellness</small></span></a>; }
function Button({ children, className = '', onClick, href, type = 'button' }) { if (href) return <a className={`button ${className}`} href={href}>{children}</a>; return <button className={`button ${className}`} type={type} onClick={onClick}>{children}</button>; }
function Header() {
  const [open, setOpen] = useState(false);
  const links = [['Services', 'services'], ['About', 'about'], ['Contact', 'contact']];
  return <header className="site-header"><div className="container header-inner"><Logo /><nav className={open ? 'nav nav--open' : 'nav'}><a href="#home" onClick={() => setOpen(false)}>Home</a>{links.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}<a href="#booking" onClick={(event) => { event.preventDefault(); setOpen(false); navigate('/booking'); }}>Booking</a><Button className="button--small" onClick={() => { setOpen(false); navigate('/booking'); }}>Book Now</Button></nav><button className="menu-toggle" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? '×' : '☰'}</button></div></header>;
}
function SectionHeading({ eyebrow, title, copy, light = false }) { return <div className={`section-heading ${light ? 'section-heading--light' : ''}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>; }
function ServiceCard({ service }) { return <article className="service-card"><div className="service-image"><img loading="lazy" src={asset(service.image)} alt={`${service.name} treatment at Happy Ending Massage Spa`} /><span className="service-number">{String(services.indexOf(service) + 1).padStart(2, '0')}</span></div><div className="service-body"><div className="service-meta"><h3>{service.name}</h3><strong>{money(service.price)}</strong></div><p>{service.description}</p><Button className="button--text" onClick={() => navigate(`/booking?service=${encodeURIComponent(service.id)}`)}>Book Now</Button></div></article>; }
function Home() {
  const [active, setActive] = useState('');
  useEffect(() => { const onScroll = () => { const ids = ['services', 'about', 'contact']; const current = ids.find((id) => { const el = document.getElementById(id); return el && window.scrollY >= el.offsetTop - 180; }); setActive(current || ''); }; window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll); }, []);
  return <><Header /><main><section className="hero"><div className="hero-image" /><div className="container hero-content"><div className="hero-copy"><span className="eyebrow">Luxury Massage & Wellness</span><h1>Noir Lotus<br /><em>Spa</em></h1><p>Premium massage experiences designed for relaxation, recovery and complete wellbeing.</p><div className="hero-actions"><Button onClick={() => document.getElementById('services').scrollIntoView({ behavior: 'smooth' })}>Book Now</Button><Button className="button--whatsapp" href={waLink}>Chat on WhatsApp</Button><Button className="button--outline" href={MAPS_URL}>Get Directions</Button></div></div></div></section><section id="about" className="about-section"><div className="container about-grid"><div className="about-photo"><img loading="lazy" src={asset('about-spa.jpg')} alt="Dark velvet spa lounge with candles and black marble" /></div><div className="about-copy"><SectionHeading eyebrow="About Us" title="A private sanctuary in the heart of Westlands" copy="Noir Lotus Spa offers professional massage and wellness experiences in a calm, private and luxurious environment. Every session is delivered by trained therapists in discreet treatment rooms designed for complete stillness." /><div className="values-grid"><div className="value-item"><span>✦</span><strong>Trained therapists</strong></div><div className="value-item"><span>✦</span><strong>Private suites</strong></div><div className="value-item"><span>✦</span><strong>Open daily</strong></div></div></div></div></section><section id="services" className="section services-section"><div className="container"><SectionHeading eyebrow="Our Treatments" title="Signature massages" copy="Choose your therapy — each session is delivered in a private, candlelit suite." /><div className="services-grid">{services.map((service) => <ServiceCard key={service.id} service={service} />)}</div></div></section><section id="contact" className="contact-section"><div className="container contact-inner"><SectionHeading eyebrow="Contact" title="Talk to us" copy="Premium massage and wellness in Westlands, Nairobi." /><div className="contact-actions"><Button href={waLink}>Chat on WhatsApp</Button><Button className="button--outline" onClick={() => navigate('/booking')}>Book Now</Button><Button className="button--outline" href="tel:0182095210">Call Us · 0182 095 210</Button><Button className="button--outline" href={MAPS_URL}>Get Directions</Button></div></div></section></main><Footer /><a className="floating-whatsapp" href={waLink} target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp">⌕</a></>;
}
function Footer() { return <footer className="footer"><div className="container footer-grid"><div><Logo compact /><p>Private massage and wellness in the heart of Westlands.</p></div><div className="footer-links"><a href="#services">Services</a><a href="/booking" onClick={(event) => { event.preventDefault(); navigate('/booking'); }}>Book a session</a><a href={waLink}>WhatsApp</a><a href="tel:0182095210">Call us</a></div><div className="footer-address"><span>Visit us</span><p>Westview Apartments,<br />School Lane, Westlands,<br />Nairobi, Kenya</p><a href={MAPS_URL}>Get directions ↗</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Noir Lotus Spa</span><span>Luxury massage & wellness</span></div></footer>; }
function Booking() {
  const params = new URLSearchParams(window.location.search); const selected = services.find((service) => service.id === params.get('service')) || services[0];
  const [form, setForm] = useState({ service: selected.id, name: '', phone: '', email: '', date: '', time: '', guests: '1', notes: '' }); const [state, setState] = useState({ status: 'idle', reference: '' });
  const current = services.find((service) => service.id === form.service) || selected;
  const update = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  async function submit(event) { event.preventDefault(); setState({ status: 'saving', reference: '' }); try { const response = await fetch('/api/bookings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, service: current.name, price: current.price }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to save booking'); setState({ status: 'success', reference: data.reference }); } catch (error) { setState({ status: 'error', reference: error.message }); } }
  if (state.status === 'success') return <><Header /><main className="booking-page"><div className="confirmation"><span className="confirmation-mark">✓</span><span className="eyebrow">Request received</span><h1>Your quiet moment<br /><em>is on its way.</em></h1><p>Your booking request <strong>{state.reference}</strong> has been received. The spa will contact you to confirm availability. It is not confirmed until you hear from our team.</p><Button onClick={() => navigate('/')}>Return home</Button></div></main><Footer /></>;
  return <><Header /><main className="booking-page"><div className="container booking-grid"><div className="booking-intro"><span className="eyebrow">Private appointments</span><h1>Reserve<br /><em>your session.</em></h1><p>Choose your preferred treatment, date and time. We will review your request and contact you with confirmation.</p><div className="booking-note"><span>01</span><p>All requests are handled discreetly by our spa team.</p></div></div><form className="booking-form" onSubmit={submit}><div className="form-heading"><span className="eyebrow">Booking details</span><h2>Tell us how to prepare.</h2></div><label>Full name<input required value={form.name} onChange={update('name')} placeholder="Your name" /></label><div className="form-row"><label>Phone number<input required type="tel" value={form.phone} onChange={update('phone')} placeholder="07xx xxx xxx" /></label><label>Email address <span>(optional)</span><input type="email" value={form.email} onChange={update('email')} placeholder="you@example.com" /></label></div><div className="form-row"><label>Service<select value={form.service} onChange={update('service')}>{services.map((service) => <option key={service.id} value={service.id}>{service.name} · {money(service.price)}</option>)}</select></label><label>Price<div className="read-only">{money(current.price)}</div></label></div><div className="form-row"><label>Preferred date<input required type="date" min={new Date().toISOString().split('T')[0]} value={form.date} onChange={update('date')} /></label><label>Preferred time<select required value={form.time} onChange={update('time')}><option value="">Choose a time</option>{['09:00', '11:00', '13:00', '15:00', '17:00', '19:00'].map((time) => <option key={time}>{time}</option>)}</select></label></div><label>Number of guests<select value={form.guests} onChange={update('guests')}><option>1</option><option>2</option><option>3</option><option>4</option></select></label><label>Notes <span>(optional)</span><textarea rows="4" value={form.notes} onChange={update('notes')} placeholder="Anything we should know before your visit?" /></label>{state.status === 'error' && <p className="form-error">{state.reference}</p>}<Button type="submit" className="button--full">{state.status === 'saving' ? 'Sending request...' : 'Confirm booking'} <span>↗</span></Button><p className="form-footnote">Your request is private and will be reviewed by the spa team.</p></form></div></main><Footer /></>;
}
function BookingFlow() {
  const params = new URLSearchParams(window.location.search);
  const selected = services.find((service) => service.id === params.get('service')) || services[0];
  const [provider, setProvider] = useState(null);
  const [form, setForm] = useState({ service: selected.id, name: '', phone: '', email: '', date: '', time: '', guests: '1', notes: '' });
  const [state, setState] = useState({ status: 'idle', reference: '' });
  const current = services.find((service) => service.id === form.service) || selected;
  const update = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  async function submit(event) {
    event.preventDefault();
    setState({ status: 'saving', reference: '' });
    try {
      const service = `${current.name} with ${provider.name}`;
      const response = await fetch('/api/bookings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, service, price: current.price }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || 'Unable to save booking');
      const message = `Hello Happy Ending Massage Spa, I would like to book a session.%0A%0AName: ${encodeURIComponent(form.name)}%0APhone: ${encodeURIComponent(form.phone)}%0ATreatment: ${encodeURIComponent(current.name)}%0APreferred therapist: ${encodeURIComponent(provider.name)}%0ADate: ${encodeURIComponent(form.date)}%0ATime: ${encodeURIComponent(form.time)}%0AGuests: ${encodeURIComponent(form.guests)}%0ANotes: ${encodeURIComponent(form.notes || 'None')}%0AReference: ${encodeURIComponent(data.reference)}`;
      window.location.href = `https://wa.me/${WA_NUMBER}?text=${message}`;
      setState({ status: 'success', reference: data.reference });
    } catch (error) { setState({ status: 'error', reference: error.message }); }
  }
  if (!provider) return <><Header /><main className="booking-page provider-page"><div className="container"><div className="provider-heading"><span className="eyebrow">Book a session</span><h1>Choose your<br /><em>therapist.</em></h1><p>Choose the therapist you would like to see. You can upload their photos later.</p></div><div className="provider-grid">{providers.map((item) => <button className="provider-card" key={item.id} type="button" onClick={() => setProvider(item)}><img src={asset(item.image)} alt={`${item.name}, massage therapist`} /><span>{item.name}</span><small>Available for appointments</small></button>)}</div></div></main><Footer /></>;
  return <><Header /><main className="booking-page"><div className="container booking-grid"><div className="booking-intro"><span className="eyebrow">{provider.name} · Private appointment</span><h1>Reserve<br /><em>your session.</em></h1><p>Choose your treatment, date and time. Your completed request will open in WhatsApp for confirmation.</p><button className="booking-back" type="button" onClick={() => setProvider(null)}>← Choose another therapist</button></div><form className="booking-form" onSubmit={submit}><div className="form-heading"><span className="eyebrow">Booking details</span><h2>Tell us how to prepare.</h2></div><label>Full name<input required value={form.name} onChange={update('name')} placeholder="Your name" /></label><div className="form-row"><label>Phone number<input required type="tel" value={form.phone} onChange={update('phone')} placeholder="07xx xxx xxx" /></label><label>Email address <span>(optional)</span><input type="email" value={form.email} onChange={update('email')} placeholder="you@example.com" /></label></div><div className="form-row"><label>Service<select value={form.service} onChange={update('service')}>{services.map((service) => <option key={service.id} value={service.id}>{service.name} · {money(service.price)}</option>)}</select></label><label>Price<div className="read-only">{money(current.price)}</div></label></div><div className="form-row"><label>Preferred date<input required type="date" min={new Date().toISOString().split('T')[0]} value={form.date} onChange={update('date')} /></label><label>Preferred time<select required value={form.time} onChange={update('time')}><option value="">Choose a time</option>{['09:00', '11:00', '13:00', '15:00', '17:00', '19:00'].map((time) => <option key={time}>{time}</option>)}</select></label></div><label>Number of guests<select value={form.guests} onChange={update('guests')}><option>1</option><option>2</option><option>3</option><option>4</option></select></label><label>Notes <span>(optional)</span><textarea rows="4" value={form.notes} onChange={update('notes')} placeholder="Anything we should know before your visit?" /></label>{state.status === 'error' && <p className="form-error">{state.reference}</p>}<Button type="submit" className="button--full">{state.status === 'saving' ? 'Sending request...' : 'Complete booking on WhatsApp'} <span>↗</span></Button><p className="form-footnote">Your request will be saved and opened in WhatsApp for confirmation.</p></form></div></main><Footer /></>;
}

function Admin() {
  const [token, setToken] = useState(sessionStorage.getItem('adminToken') || ''); const [password, setPassword] = useState(''); const [bookings, setBookings] = useState([]); const [filters, setFilters] = useState({ status: '', service: '', date: '' });
  async function login(event) { event.preventDefault(); const response = await fetch('/api/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); const data = await response.json(); if (response.ok) { sessionStorage.setItem('adminToken', data.token); setToken(data.token); } else alert(data.error); }
  async function load() { const query = new URLSearchParams(filters); const response = await fetch(`/api/admin/bookings?${query}`, { headers: { Authorization: `Bearer ${token}` } }); if (response.ok) setBookings(await response.json()); }
  useEffect(() => { if (token) load(); }, [token, filters.status, filters.service, filters.date]);
  async function updateStatus(id, status) { await fetch(`/api/admin/bookings/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ status }) }); load(); }
  if (!token) return <main className="admin-login"><form onSubmit={login} className="admin-login-card"><Logo /><span className="eyebrow">Private access</span><h1>Booking desk</h1><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Admin password" required /><Button type="submit" className="button--full">Sign in</Button></form></main>;
  return <main className="admin-page"><div className="admin-top"><Logo compact /><div><span className="eyebrow">Private admin</span><h1>Booking desk</h1></div><Button className="button--outline" onClick={() => { sessionStorage.removeItem('adminToken'); setToken(''); }}>Sign out</Button></div><div className="admin-toolbar"><input type="date" value={filters.date} onChange={(event) => setFilters({ ...filters, date: event.target.value })} /><select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="">All statuses</option><option>PENDING</option><option>CONFIRMED</option><option>COMPLETED</option><option>CANCELLED</option></select><select value={filters.service} onChange={(event) => setFilters({ ...filters, service: event.target.value })}><option value="">All services</option>{services.map((service) => <option key={service.id}>{service.name}</option>)}</select></div><div className="booking-table-wrap"><table><thead><tr><th>Reference</th><th>Guest</th><th>Service</th><th>Date / time</th><th>Price</th><th>Status</th><th>Notes</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking.id}><td><strong>{booking.reference}</strong></td><td>{booking.name}<small>{booking.phone}</small></td><td>{booking.service}</td><td>{booking.date}<small>{booking.time}</small></td><td>{money(booking.price)}</td><td><select value={booking.status} onChange={(event) => updateStatus(booking.id, event.target.value)}><option>PENDING</option><option>CONFIRMED</option><option>COMPLETED</option><option>CANCELLED</option></select></td><td>{booking.notes || '—'}</td></tr>)}</tbody></table>{!bookings.length && <p className="empty-state">No booking requests match these filters.</p>}</div></main>;
}
function App() { const [, refresh] = useState(0); useEffect(() => { const onPop = () => refresh((value) => value + 1); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop); }, []); if (window.location.pathname === '/booking') return <BookingFlow />; if (window.location.pathname === '/admin') return <Admin />; return <Home />; }

createRoot(document.getElementById('root')).render(<App />);
